### PR TITLE
Validate EventListener trigger name as label value

### LINKED ISSUE #382: Resource creation fails as label name does not conform to k8s requirements
# Expected Behavior

If I am allowed to call a trigger "a/b/c/d" then the triggers code should not later fail.

# Actual Behavior

The eventlistener pod errors with a naming issue

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:150","msg":"couldn't create resource with group version kind \"tekton.dev/v1alpha1, Resource=pipelineresources\": PipelineResource.tekton.dev \"pull-request-7bszb\" is invalid: metadata.labels: Invalid value: \"github.foo.com/foo/node-sample\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')","knative.dev/controller":"eventlistener","/triggers-eventid":"2gkkv","/trigger":"github.foo.com/foo/node-sample","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/Users/foo/Work/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:150\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/Users/foo/Work/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:93"}
```
  

The addLabels code is simply taking the triggername and using it as a label value:
https://github.com/tektoncd/triggers/blob/63f3badc8dbce481bfd2bee3f13d433815447c76/pkg/resources/create.go#L72  

Unsure whether the action to take here is to document the restriction and validate the name during trigger creation or to alter the name in the label.   If the former, then this should be considered a breaking change(?)

# Steps to Reproduce the Problem

1. Create a trigger in your eventlistener with the name a/b/c/d
2. Create a pipelineresource in the associated triggertemplate
3. Poke your trigger into action

# Additional Info

### PR DESCRIPTION
**Pull request by ncskier**
# Changes
Fixes #382
Since we use the EventListener trigger name as the `tekton.dev/trigger`
label, we must validate the trigger name as if it is a label value.
This PR makes webhook validation fail when the trigger name is not a
valid k8s label value.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

File: pkg/apis/triggers/v1alpha1/event_listener_validation.go [hunk 1]
```diff
@@ -34,42 +35,58 @@ func (s *EventListenerSpec) validate(ctx context.Context, el *EventListener) *ap
...
+		if err := interceptor.validate(ctx).ViaField(fmt.Sprintf("interceptors[%d]", i)); err != nil {
+			return err
 		}
 	}
+
+	// The trigger name is added as a label value for 'tekton.dev/trigger' so it must follow the k8s label guidelines:
+	// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
+	maxLength := 63
+	labelValueRegexp := regexp.MustCompile(`^([a-z0-9A-Z]([a-z0-9A-Z-_.]*[a-z0-9A-Z])?){0,63}$`)
+	if !(labelValueRegexp.MatchString(t.Name) && len(t.Name) <= maxLength) {
```
Comment (dibyom) [inline pkg/apis/triggers/v1alpha1/event_listener_validation.go]: The code looks fine but maybe we can get away with using the validator from the k8s library like we do in pipeline? https://github.com/tektoncd/pipeline/blob/242bb06a05bc698d4c43b120fa050be2dbe7a99c/pkg/apis/pipeline/v1alpha1/task_validation.go#L97

Comment (ncskier) [reply pkg/apis/triggers/v1alpha1/event_listener_validation.go]: Oh, cool! That looks a lot better! 👍
