### PR TITLE
Preserve escaped characters when parsing json path 🦟

### LINKED ISSUE #258: Values injected into the template should be escaped
# Expected Behavior

It should be possible for me to pass along the body of a github pull request event to a TaskRun + Task.

# Actual Behavior

When I'm trying to trigger from a pull request and pass along the description of the pull request to a Task, I run into trouble b/c the description contains characters like `\r` and `\n` and I can't figure out how to escape this in the template properly :S

# Steps to Reproduce the Problem

Example trigger binding I was using:

```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bobcatfish-review-pipelinebinding
spec:
  params:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: pullrequesturl
      value: $(body.pull_request.html_url)
    - name: body
      value: $(body.pull_request.body) # <-- this is where im getting the description of the pull request
```

Here is an example of the body field of the pull request:

```json
"body": "# Changes\r\n\r\nHI THERE HAHAHA HAHAHA\r\n\r\n# Submitter Checklist\r\n\r\nThese are the criteria that every PR should meet, please check them off as you\r\nreview them:\r\n\r\n- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)\r\n- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)\r\n- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)\r\n\r\n_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._\r\n\r\nDouble check this list of stuff that's easy to miss:\r\n\r\n- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update\r\n  [the release Task](../tekton/publish.yaml) to build and release this image.\r\n\r\n## Reviewer Notes\r\n\r\nIf [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).\r\n\r\n# Release Notes\r\n\r\n```\r\nDescribe any user facing changes here, or delete this block.\r\n\r\nExamples of user facing changes:\r\n- API changes\r\n- Bug fixes\r\n- Any changes in behavior\r\n\r\n```\r\n",
```

Here is the template I was trying to use:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bobcatfish-review-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: pullrequesturl
      description: The url of the pull reuqest
    - name: body
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: pr-$(uid)
      spec:
        type: pullRequest
        params:
        - name: url
          value: $(params.pullrequesturl)
        secrets:
        - secretName: webhook-secret
          secretKey: token
          fieldName: githubToken
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: source-repo-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        name: tr-bobcatfish-review-$(uid)
      spec:
        taskRef:
          name: release-notes
        inputs:
          params:
          - name: message
            value: $(params.body) # <-- this is where it all falls apart
          resources:
            - name: repo
              resourceRef:
                name: source-repo-$(uid)
```

I end up with an error like:

```
"the object provided is unrecognized (must be of type TaskRun): couldn't get version/kind; json parse error: invalid character '\r' in string literal ({"apiVersion":"tekton.dev/v1al ...)" 
```

# Additional Info

I can't tell if this is a bug or (I'm hoping!) there is some way I can specify the `$(params.body)` in the trigger template such that the values being passed along can be properly escaped.

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

I was trying to use Triggers to deliver a payload that included some
newlines and carriage returns into the value of a Pipeline param, but
along the way they were being turned from actual \ + n to the newline
character, etc., which when embedded into the yaml of the CRD I wanted
to create was invalid.

Now we will treat json strings as json when using the values via json
path instead of decoding the the escaped characters.

Dropping the quotation marks seems like a pretty big hack but it's the
best option we could think of and seems to consistently give us the
results we'd expect as users.

Co-authored-by: Dibyo Mukherjee <dibyo@google.com>

Fixes #258 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Can now handle using json path to extract payloads that contain escape sequences such as \r and \n
```

### CODE REVIEW

File: pkg/resources/create_test.go [hunk 1]
```diff
@@ -139,22 +139,12 @@ func TestCreateResource(t *testing.T) {
...
-				APIVersion: "tekton.dev/v1alpha1",
-				Kind:       "PipelineResource",
-			},
-			ObjectMeta: metav1.ObjectMeta{
-				Name:   "my-pipelineresource",
-				Labels: map[string]string{"woriginal-label-1": "label-1"},
-			},
-			Spec: pipelinev1.PipelineResourceSpec{},
-		},
+		json: json.RawMessage("{\"kind\":\"PipelineResource\",\"apiVersion\":\"tekton.dev/v1alpha1\",\"metadata\":{\"name\":\"my-pipelineresource\",\"creationTimestamp\":null,\"labels\":{\"woriginal-label-1\":\"label-1\"}},\"spec\":{\"type\":\"\",\"params\":[{\"name\":\"foo\",\"value\":\"bar\\r\\nbaz\"}]},\"status\":{}}"),
```
Comment (dibyom) [inline pkg/resources/create_test.go]: Could we use raw strings `` here...then we could lose the escaping around the quotes `"`?

File: pkg/template/event_test.go [hunk 2]
```diff
@@ -315,6 +316,61 @@ func Test_NewResources(t *testing.T) {
...
+			},
+		}},
+	}}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			params, err := ResolveParams(tt.bindings, tt.body, map[string][]string{}, tt.params)
+			if err != nil {
+				t.Fatalf("ResolveParams() returned unexpected error: %s", err)
+			}
+			trans := cmp.Transformer("Sort", func(in []pipelinev1.Param) []pipelinev1.Param {
```
Comment (dibyom) [inline pkg/template/event_test.go]: Could we use `cmpopts.SortSlices` here as we do in `resource_test.go`?
https://github.com/tektoncd/triggers/blob/5d31c9600537b0dc5b89f77eded8c1ecdc861c52/pkg/template/resource_test.go#L117

File: pkg/template/jsonpath.go [hunk 3]
```diff
@@ -89,7 +89,16 @@ func textValue(v reflect.Value) ([]byte, error) {
 
 	switch t.Kind() {
 	// evalToText() returns <map> ....; return JSON string instead.
-	case reflect.Map, reflect.Slice:
+	case reflect.String:
```
Comment (dibyom) [inline pkg/template/jsonpath.go]: I wonder if we can always use `json.Marshal` and get rid of the `evalToText` altogether....we'd still need a special case for strings to remove the quotes but for every other type I think using `json.Marshal` would give us what we want! 
(Just a thought.....if we decide to do this, we should do it in a followup)

File: pkg/template/jsonpath_test.go [hunk 4]
```diff
@@ -9,7 +9,7 @@ import (
 	"github.com/google/go-cmp/cmp"
 )
 
-var objects = `{"a":"v","c":{"d":"e"},"empty": "","null": null, "number": 42}`
+var objects = `{"a":"v\r\n烈","c":{"d":"e"},"empty": "","null": null, "number": 42}`
```
Comment (dibyom) [inline pkg/template/jsonpath_test.go]: :100:

File: test/eventlistener_test.go [hunk 5]
```diff
@@ -46,8 +47,19 @@ const (
 	resourceLabel = triggersv1.GroupName + triggersv1.EventListenerLabelKey
 	triggerLabel  = triggersv1.GroupName + triggersv1.TriggerLabelKey
 	eventIDLabel  = triggersv1.GroupName + triggersv1.EventIDLabelKey
+
+	examplePRJsonFilename = "pr.json"
 )
 
+func loadExamplePREventBytes() ([]byte, error) {
```
Comment (dibyom) [inline test/eventlistener_test.go]: This is great! I think we should have more tests that use actual event payload...and not just in the e2e test but also in the sink tests!

**Comment by dibyom** [comment]
> I1216 15:25:23.555]         {"level":"error","logger":"eventlistener","caller":"sink/sink.go:126","msg":"Could not create resources for \"\": couldn't create resource with group version kind \"tekton.dev/v1alpha1, Resource=pipelineresources\": PipelineResource.tekton.dev \"pr2\" is invalid: metadata.labels: Invalid value: \"3.52140673e+08\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","knative.dev/controller":"eventlistener","/triggers-eventid":"xj489","/trigger":"","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:126"}

:thinking:

File: test/eventlistener_test.go [hunk 6]
```diff
@@ -111,10 +124,11 @@ func TestEventListenerCreate(t *testing.T) {
 		bldr.TriggerTemplate("my-triggertemplate", "",
 			bldr.TriggerTemplateSpec(
 				bldr.TriggerTemplateParam("oneparam", "", ""),
-				bldr.TriggerTemplateParam("twoparamname", "", ""),
+				bldr.TriggerTemplateParam("twopgo test -v -tags=e2e -count=1 ./test -run ^TestEventListeneraramname", "", ""),
```
Comment (dibyom) [inline test/eventlistener_test.go]: Is this intentional? As in do we expect the name (and not the value) of a template param to contain spaces and special chars?

File: pkg/resources/create.go [hunk 7]
```diff
@@ -100,8 +100,12 @@ func Create(logger *zap.SugaredLogger, rt json.RawMessage, triggerName, eventID,
 		Resource: apiResource.Name,
 	}
 
-	_, err = dc.Resource(gvr).Namespace(namespace).Create(data, metav1.CreateOptions{})
-	return err
+	logger.Infof("Creating resource with payload: %v", data)
```
Comment (dibyom) [inline pkg/resources/create.go]: I wonder if should be logging the whole payload here...just looking at the integration test logs, the payload can he huge (especially if we are passing through large chunks of the incoming body)....maybe we log the gvk and the eventID by default...and if the resource creation fails, then we log the whole payload? (Another option would be to log at the Debug level instead of Info)

File: test/eventlistener_test.go [hunk 8]
```diff
@@ -245,8 +266,10 @@ func TestEventListenerCreate(t *testing.T) {
 		Spec: v1alpha1.PipelineResourceSpec{
 			Type: "git",
 			Params: []v1alpha1.ResourceParam{
-				{Name: "body", Value: strings.Replace(`{"one": "zonevalue", "two": {"name": "zfoo", "value": "bar"}}`, " ", "", -1)},
```
Comment (dibyom) [inline test/eventlistener_test.go]: I think this `zonevalue` came from the previous body, so we'd have to replace all instances of it

File: test/eventlistener_test.go (hunk 6 above)
Comment (bobcatfish) [reply test/eventlistener_test.go]: lol NO

Comment (bobcatfish) [reply test/eventlistener_test.go]: something is going on lately where i randomly paste into my IDE _all the time_. i need to get to the bottom of this XD

**Comment by bobcatfish** [comment]
```
I1216 15:21:26.950] level=warning msg="[runner] Can't run linter goanalysis_metalinter: ctrlflow: failed prerequisites: inspect@github.com/tektoncd/triggers/test/builder [github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1.test]"
I1216 15:21:26.951] level=error msg="Timeout exceeded: try increase it by passing --timeout option"
```

wut

File: pkg/resources/create_test.go (hunk 1 above)
Comment (bobcatfish) [reply pkg/resources/create_test.go]: good call! :D

File: pkg/template/event_test.go (hunk 2 above)
Comment (bobcatfish) [reply pkg/template/event_test.go]: ah kk that's simpler, i didnt know about that!! only downside i can think of is that'll sort any slice, not just pipeline params? maybe thats actually a good thing - usually we don't care about order

Comment (bobcatfish) [reply pkg/template/event_test.go]: > only downside i can think of is that'll sort any slice, not just pipeline params? maybe thats actually a good thing - usually we don't care about order

nvm, just saw the value of compareParam! no downsides at all :D

File: pkg/template/jsonpath.go (hunk 3 above)
Comment (bobcatfish) [reply pkg/template/jsonpath.go]: ah interesting idea! ill see what happens to our test cases at least :D

**Comment by bobcatfish** [comment]
> :thinking:

whoops i think i was using a value for a label that I shouldnt XD

File: pkg/resources/create.go (hunk 7 above)
Comment (bobcatfish) [reply pkg/resources/create.go]: ah yeah good call - ill make it shorter for now. as a follow up, i think it could be useful to make these payloads available on disk somewhere for debugging (i hacked that into the github interceptor to get this payload)

File: test/params.go [hunk 9]
```diff
@@ -0,0 +1,27 @@
...
+limitations under the License.
+*/
+
+package test
+
+import (
+	pipelinev1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
+)
+
+// CompareParams can be used with comparison options such as `cmpopts.SortSlices`
```
Comment (dibyom) [inline test/params.go]: nice!!

File: test/eventlistener_test.go [hunk 10]
```diff
@@ -348,3 +369,40 @@ func TestEventListenerCreate(t *testing.T) {
...
+	spdx_id string
+	url     string
+	node_id string
+}
+
+// compareParamsWithLicenseJSON will compare the passed in ResourceParams by further checking
+// when the values aren't equal if they can be unmarshalled into the license object and if they are
+// then equal. This is because the order of values in a dictionary is not deterministic and dictionary
+// values passed through an event listener may change order.
+func compareParamsWithLicenseJSON(x, y v1alpha1.ResourceParam) bool {
```
Comment (dibyom) [inline test/eventlistener_test.go]: Is this different from unmarshalling and then using cmp.Diff?

Comment (bobcatfish) [reply test/eventlistener_test.go]: Okay now im unmarshalling + then using cmp.Diff! Most of the function remains the same but now I don't have to manually check all the fields.

I feel like I'm slowly starting to understand how all the unmarshalling and marshalling works - cant wait to stop working on it and forget in 6 months X'D

**Comment by bobcatfish** [comment]
PLEASE LINTER PLEASE

**Comment by bobcatfish** [comment]
cat asking nicely
