### PR TITLE
Ignore spec.clusterIP when reconciling Service

### LINKED ISSUE #103: EventListener reconciler fails service reconciliation
# Expected Behavior
Reconcile should succeed.

# Actual Behavior
If we update an EventListener, the deployment reconciliation succeeds but the service reconcile fails with the following:

```
{"level":"error","logger":"controller.eventlistener-controller","caller":"eventlistener/eventlistener.go:202","msg":"Error updating EventListener Service: Service \"listener\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable","knative.dev/controller":"eventlistener-controller","stacktrace":"github.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).Reconcile\n\t/usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:202\ngithub.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go:330\ngithub.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).Run.func1\n\t/usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go:282"}

{"level":"error","logger":"controller.eventlistener-controller","caller":"controller/controller.go:345","msg":"Reconcile error","knative.dev/controller":"eventlistener-controller","error":"Service \"listener\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable","stacktrace":"github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\t/usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go:345\ngithub.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go:331\ngithub.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).Run.func1\n\t/usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go:282"}
```

# Steps to Reproduce the Problem

1. Create an event listener
2. Update the event listener spec (e.g. modify the service account)
3. Look in controller logs for the failure

# Additional Info

/kind bug

### PR DESCRIPTION
**Pull request by dibyom**
# Changes
The `clusterIP` field is usually set by the k8s master
and cannot be updated once set. This commit ignores the
clusterIP when comparing the desired and current service
specs. Without this, we would always try to update the service
and fail.

Fixes #103 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

File: pkg/reconciler/v1alpha1/eventlistener/eventlistener.go [hunk 1]
```diff
@@ -194,15 +194,21 @@ func (c *Reconciler) Reconcile(ctx context.Context, key string) error {
...
-			c.Logger.Errorf("Error updating EventListener Service: %s", err)
-			return err
+	} else {
+		// clusterIP cannot be updated once set. So, ignore it when comparing the serviceSpecs
+		if oldService.Spec.ClusterIP != "" {
+			service.Spec.ClusterIP = oldService.Spec.ClusterIP
+		}
+		if !reflect.DeepEqual(oldService.Spec, service.Spec) {
+			// Update the EventListener Service
+			oldService.Spec = service.Spec
```
Comment (vtereso) [inline pkg/reconciler/v1alpha1/eventlistener/eventlistener.go]: This is setting the old spec to the new spec (same as before), which doesn't have the clusterIP value. Easy fix should be to only set the necessary values piecemeal. This was mostly a convenient recycling of the deployment reconciliation because there is more values nested within that spec. The only thing that matter for the service is likely labels.
