### PR TITLE
fix panic in github interceptor

### LINKED ISSUE #355: invalid memory address or nil pointer dereference on `v0.2.0`
# Expected Behavior
A PipelineRun should be created when sending a webhook from Github.

# Actual Behavior
The event listener errors out with an `invalid memory address or nil pointer dereference` panic.

# Steps to Reproduce the Problem

1. Create an event listener with a Github interceptor using `v0.2.0` syntax.
2. Send the webhook.
3. Check the logs for the error.

# Additional Info
I'm using similar markup to what's in the example in this repo for the `TriggerBinding`. The listener is pretty simple as well.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-trigger
spec:
  params:
  - name: gitrevision
    description: The git revision
  - name: gitrepositoryurl
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-
    spec:
      serviceAccountName: service-ci
      pipelineRef:
        name: plugin-pipeline
      params:
      - name: sourceLocation
        value: location
      resources:
      - name: workspace
        resourceSpec:
          type: git
          params:
          - name: url
            value: $(params.gitrepositoryurl)
          - name: revision
            value: $(params.gitrevision)
      - name: dockerImage
        resourceSpec:
          type: image
          params:
          - name: url
            value: my-awesome-image
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-trigger
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-trigger
spec:
  serviceAccountName: trigger-listener
  triggers:
  - name: github-repo-information
    interceptors:
    - github:
        secretRef:
          secretName: github-shared-secret
          secretKey: shared
          namespace: tekton-pipelines
        eventTypes:
        - push
    bindings:
    - name: pipeline-trigger
    template:
      name: pipeline-trigger
```

Here are the logs I'm getting. It appears to be an issue with the request being passed down to the interceptor.

```
{"level":"info","caller":"logging/config.go:100","msg":"Successfully created the logger.","knative.dev/jsonconfig":"{\"level\": \"info\",\"development\": false,\"sampling\": {\"initial\": 100,\"thereafter\": 100},\"outputPaths\": [\"stdout\"],\"errorOutputPaths\": [\"stderr\"],\"encoding\": \"json\",\"encoderConfig\": {\"timeKey\": \"\",\"levelKey\": \"level\",\"nameKey\": \"logger\",\"callerKey\": \"caller\",\"messageKey\": \"msg\",\"stacktraceKey\": \"stacktrace\",\"lineEnding\": \"\",\"levelEncoder\": \"\",\"timeEncoder\": \"\",\"durationEncoder\": \"\",\"callerEncoder\": \"\"}}"}
{"level":"info","caller":"logging/config.go:101","msg":"Logging level set to info"}
{"level":"info","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","logger":"eventlistener","caller":"logging/logging.go:46","msg":"Starting the Configuration eventlistener","knative.dev/controller":"eventlistener"}
{"level":"info","logger":"eventlistener","caller":"eventlistenersink/main.go:71","msg":"EventListener pod started","knative.dev/controller":"eventlistener"}
{"level":"info","logger":"eventlistener","caller":"eventlistenersink/main.go:97","msg":"Listen and serve on port 8080","knative.dev/controller":"eventlistener"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x128e438]

goroutine 35 [running]:
github.com/tektoncd/triggers/pkg/interceptors/github.(*Interceptor).ExecuteTrigger(0xc00031e360, 0xc00047a300, 0x0, 0x0, 0x0)
	/workspace/go/src/github.com/tektoncd/triggers/pkg/interceptors/github/github.go:56 +0x3c8
github.com/tektoncd/triggers/pkg/sink.Sink.executeInterceptors(0x18685c0, 0xc00009e120, 0x180dc20, 0xc0005a4160, 0x7f90477886b0, 0xc0005857e0, 0x17eb0e0, 0xc00022a2b8, 0x1824720, 0xc0005859c0, ...)
	/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:179 +0x171
github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger(0x18685c0, 0xc00009e120, 0x180dc20, 0xc0005a4160, 0x7f90477886b0, 0xc0005857e0, 0x17eb0e0, 0xc00022a2b8, 0x1824720, 0xc0005859c0, ...)
	/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:129 +0x1f9
github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1(0x18685c0, 0xc00009e120, 0x180dc20, 0xc0005a4160, 0x7f90477886b0, 0xc0005857e0, 0x17eb0e0, 0xc00022a2b8, 0x1824720, 0xc0005859c0, ...)
	/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:93 +0xd2
created by github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent
	/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:92 +0x79d
```

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

We were passing the original request where the body had been drained
to the first interceptor meaning that the body to the first interceptor
in the chain was always empty. Further, we were using the `GetBody` which
can sometimes be empty leading to a panic.

fixes #355

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Fixes bug that caused panic when Github interceptor was used as the first interceptor
```

### CODE REVIEW

**Comment by bobcatfish** [comment]
https://github.com/tektoncd/plumbing/issues/186 is hitting here too :(

File: pkg/sink/sink_test.go [hunk 1]
```diff
@@ -231,6 +231,189 @@ func TestHandleEvent(t *testing.T) {
 	}
 }
 
+func TestHandleEventWithInterceptors(t *testing.T) {
```
Comment (vtereso) [inline pkg/sink/sink_test.go]: This is repeating `TestHandleEvent` with only a few differences. We could use a testing table so that we could test [0-2] interceptors in a bit less verbose way. This seems fine though.

Comment (dibyom) [reply pkg/sink/sink_test.go]: Yeah long term, I want to extract the common bits out into a couple of helper methods that create the required resources, and the clients (like we do in the reconciler tests in pipeline). For this PR though, I wanted to keep the non-fix changes to a minimum

File: pkg/interceptors/cel/cel.go [hunk 2]
```diff
@@ -58,12 +59,8 @@ func (w *Interceptor) ExecuteTrigger(request *http.Request) (*http.Response, err
 		return nil, fmt.Errorf("error creating cel environment: %w", err)
 	}
 
-	body, err := request.GetBody()
-	if err != nil {
-		return nil, fmt.Errorf("error getting request body: %w", err)
-	}
-	defer body.Close()
-	payload, err := ioutil.ReadAll(body)
+	defer request.Body.Close()
```
Comment (wlynch) [inline pkg/interceptors/cel/cel.go]: This still runs the risk of panicking if request or Body is nil. We probably want to have checks here to handle gracefully.

Example - https://play.golang.org/p/oYUtY68zw7s

Comment (dibyom) [reply pkg/interceptors/cel/cel.go]: Good point; let me add some checks

Comment (dibyom) [reply pkg/interceptors/cel/cel.go]: testing this is going to require us to refactor our tests a bit...gonna make this a new commit in this PR!

File: pkg/interceptors/cel/cel.go [hunk 3]
```diff
@@ -58,15 +59,15 @@ func (w *Interceptor) ExecuteTrigger(request *http.Request) (*http.Response, err
...
 
-	body, err := request.GetBody()
-	if err != nil {
-		return nil, fmt.Errorf("error getting request body: %w", err)
-	}
-	defer body.Close()
-	payload, err := ioutil.ReadAll(body)
-	if err != nil {
-		return nil, fmt.Errorf("error reading request body: %w", err)
+	var payload = []byte(`{}`)
```
Comment (wlynch) [inline pkg/interceptors/cel/cel.go]: I don't feel too strongly about this, but should we be consistent with the webhook handler and default to []byte{}?

Comment (dibyom) [reply pkg/interceptors/cel/cel.go]: Sure, we'd have to do it the other way around though since `makeCelEnv` errors out if you pass it []byte{}
