### PR TITLE
Delete config maps

### LINKED ISSUE #209: Default logging configuration ConfigMap not removed
# Expected Behavior

The default logging configuration ConfigMap is created when the EventListener is created in the namespace and it doesn't exist.  It should be removed when the last EventListener is removed in the namespace.

# Actual Behavior

The default  logging configuration ConfigMap is not removed after the last EventListener in the namespace is removed.
# Steps to Reproduce the Problem

1. Create a namespace
2. Create an EventListner in the namespace
3. Remove the EventListener

# Additional Info

### PR DESCRIPTION
**Pull request by bigkevmcd**
# Changes

This triggers a deletion of the automatically created logging config map when there are no more event-listeners in the namespace.

Fixes #209

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
- The automatically created logging config-map is now deleted when there are no more event-listeners in a namespace.
```

### CODE REVIEW

**Comment by bigkevmcd** [comment]
I'm not sure why this is failing, it doesn't seem to be related to my changes?

File: test/e2e-tests-ingress.sh [hunk 1]
```diff
@@ -34,7 +34,8 @@ function wait_until_taskrun_completed() {
     case ${reason} in
     "TaskRunValidationFailed"|"TaskRunTimeout")
       echo -e "\n\nERROR: ${reason}"
-      kubectl get taskrun $1 -o=jsonpath='{.status.conditions[0].message}'
+      # kubectl get taskrun $1 -o=jsonpath='{.status.conditions[0].message}'
+      kubectl get taskrun $1 -o yaml
```
Comment (dibyom) [inline test/e2e-tests-ingress.sh]: Was this intentional?

Comment (bigkevmcd) [reply test/e2e-tests-ingress.sh]: There's a flaky failing test in the taskrun setup, I've dropped this commit, but the tests are failing integration tests are failing intermittently.

Comment (bigkevmcd) [reply test/e2e-tests-ingress.sh]: And yes, a logger config per event listener does sound useful.

The code also fixes a typo in the logging file `"\"developmen\": false,"`

Comment (dibyom) [reply test/e2e-tests-ingress.sh]: Interesting. Opened https://github.com/tektoncd/triggers/issues/254 to investigate

**Comment by dibyom** [comment]
hmmm.... don't think I have seen this one before:

```
I1206 21:04:06.583] ERROR: TaskRunValidationFailed
I1206 21:04:06.736] invalid input params: param types don't match the user-specified type: [Service ServiceUID]
```

**Comment by bigkevmcd** [comment]
> hmmm.... don't think I have seen this one before:
> 
> ```
> I1206 21:04:06.583] ERROR: TaskRunValidationFailed
> I1206 21:04:06.736] invalid input params: param types don't match the user-specified type: [Service ServiceUID]
> ```

Yeah, it's weird, unfortunately I am not experienced enough to know what's going on there.

**Comment by dibyom** [comment]
I'm looking into it!
