### PR TITLE
Sync lister informers before serving traffic

### LINKED ISSUE #896: EventListener sometimes fails to resolve binding
Hi,

for our tekton deployment, sometimes we see EventListeners failing to process events with the following information in the log

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:225","msg":"failed to resolve bindings: error getting TriggerBinding : triggerbinding.triggers.tekton.dev \"visit-management-system-vmsbackend-pr\" not found","knative.dev/controller":"eventlistener","/triggers-eventid":"pprlz","/trigger":"visit-management-system-vmsbackend-pr","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:225\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:129"}
```

The mentioned TriggerBinding however exists. Do you have an idea why this fails sometimes? Is there anything i can check?

Thanks, Fabian

EventListener
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: "2020-12-21T15:43:58Z"
  finalizers:
  - eventlisteners.triggers.tekton.dev
  generation: 1
  labels:
    beekeeper/scope: Namespace
  name: visit-management-system-vmsbackend
  namespace: site-itscb
  ownerReferences:
  - apiVersion: beekeeper.sap.it/v1alpha1
    kind: NeoJavaApplication
    name: visit-management-system-vmsbackend
    uid: e5d1c689-4531-482e-8d32-a783e0def219
  resourceVersion: "438851105"
  selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/site-itscb/eventlisteners/visit-management-system-vmsbackend
  uid: 542a307f-b1cb-48e8-8173-09498e073441
spec:
  podTemplate: {}
  resources: {}
  serviceAccountName: tekton-triggers-listener
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: visit-management-system-vmsbackend-ci-master
    interceptors:
    - cel:
        filter: body.ref == 'refs/heads/master'
    name: visit-management-system-vmsbackend-ci-master
    template:
      name: visit-management-system-vmsbackend-ci-master
  - bindings:
    - kind: TriggerBinding
      ref: visit-management-system-vmsbackend-pr
    interceptors:
    - cel:
        filter: body.ref != 'refs/heads/master'
    name: visit-management-system-vmsbackend-pr
    template:
      name: visit-management-system-vmsbackend-pr
status:
  address:
    url: http://el-visit-management-system-vmsbackend.site-itscb.svc.cluster.local:8080
  conditions:
  - lastTransitionTime: "2021-01-13T11:05:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-13T11:05:21Z"
    message: Deployment exists
    status: "True"
    type: Deployment
  - lastTransitionTime: "2021-01-07T17:12:03Z"
    message: ReplicaSet "el-visit-management-system-vmsbackend-c57b9949b" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-01-13T11:05:21Z"
    message: Service exists
    status: "True"
    type: Service
  configuration:
    generatedName: el-visit-management-system-vmsbackend
```

TriggerBinding
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: "2020-12-21T15:57:59Z"
  generation: 1
  labels:
    beekeeper/scope: NeoJavaApplication-visit-management-system-vmsbackend
  name: visit-management-system-vmsbackend-pr
  namespace: site-itscb
  ownerReferences:
  - apiVersion: beekeeper.sap.it/v1alpha1
    kind: NeoJavaApplication
    name: visit-management-system-vmsbackend
    uid: e5d1c689-4531-482e-8d32-a783e0def219
  resourceVersion: "350591728"
  selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/site-itscb/triggerbindings/visit-management-system-vmsbackend-pr
  uid: 8d13d32b-9c9b-4833-83c1-b9fd9b65bb24
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
```

# Additional Info

- Kubernetes version: `v1.18.12`
- Tekton Pipeline version: `v0.19.0`
- Tekton Triggers version: `v0.10.2`

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Previously, we had a race where the EL would start serving traffic
before the lister caches were synced. This leads to the intermittent
resolution issues described in #896. #977 was an attempt to fix this for
the EventListener resource. This commit fixes it for all resource types
by first registering all the listers, and then syncing the cache before
serving traffic.

Tested by modifying the e2e test to run the intermittently failing test
10 times. Without this fix, it fails while with it it does not (See #1012).

Fixes #896

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

File: cmd/eventlistenersink/main.go [hunk 1]
```diff
@@ -86,47 +83,44 @@ func main() {
...
-		Jitter:   0.3,
-		Steps:    10,
-		Cap:      5 * time.Second,
-	}
-	err = r.WaitForEventListener(eventListenerBackoff)
-	if err != nil {
-		logger.Fatal(err)
+
+	// Start and sync the informers before we start taking traffic
+	// TODO: maybe we should have a timeout here?
```
Comment (jmcshane) [inline cmd/eventlistenersink/main.go:115]: I think something like a 15 second timeout makes sense here

Comment (wlynch) [reply cmd/eventlistenersink/main.go:115]: In lieu of a timeout, do we have any way to bubble back status to the user to say "we're starting up but we're not healthy / not able to server traffic yet"?

Comment (dibyom) [reply cmd/eventlistenersink/main.go:115]: Yeah, we don't start listening on the port until the sync is complete. This includes the /live endpoint at the moment (which we use for health checks) --> might have to think through this one a bit more so that we don't end up with endless restart loops if the sync takes too long.

We could try 
1. printing out a log message that we are starting up
2. modify the live endpoint so that we return the above starting up message

Comment (jmcshane) [reply cmd/eventlistenersink/main.go:115]: you could start a goroutine ahead of this that prints out a log line every 5-10s providing some sort of "wait for startup" message. then, cancel the routine after the cache sync has completed in line 123 below.

i think the behavior is correct to not start passing the `/live` check until the informers are fully synced. we can provide default liveness probe settings that will wait for an appropriate time before attempting to restart the pod (or startup probe, but I think we still need to support kube < 1.18).

**Review by wlynch — APPROVED** [review]

File: cmd/eventlistenersink/main.go (hunk 1 above)
Comment (dibyom) [reply cmd/eventlistenersink/main.go:115]: ok, so reading through the code, the sync function will keep going till the stop channel is closed. I'll change the call to pass in a context with a timeout of 1 min which should ensure we don't try forever.

Comment (dibyom) [reply cmd/eventlistenersink/main.go]: Updated and manually tested out that the timeout works.

**Comment by afrittoli** [comment]
This looks great, thank you!

**Review by savitaashture — COMMENTED** [review]
/lgtm
